type Contact @collection(name: "contacts") {
  firstName: String!
  lastName: String!
  age: Int!
  address: Address
  email: String!
  phone: String!
}

type Address @embedded {
  street: String!
  city: String!
  state: String!
  zipCode: String!
}

type Query {
  allContacts: [Contact!]!
}
